-- Run as the new account's owner. No account-wide billing or network changes.
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS {{ROLE}};
GRANT ROLE {{ROLE}} TO ROLE SYSADMIN;
GRANT ROLE {{ROLE}} TO USER {{LOGIN}};
CREATE RESOURCE MONITOR IF NOT EXISTS {{MONITOR}} WITH
 CREDIT_QUOTA={{QUOTA}} FREQUENCY=DAILY START_TIMESTAMP=IMMEDIATELY
 TRIGGERS ON 80 PERCENT DO NOTIFY
          ON 90 PERCENT DO SUSPEND
          ON 100 PERCENT DO SUSPEND_IMMEDIATE;
CREATE WAREHOUSE IF NOT EXISTS {{WH}} WITH
 WAREHOUSE_SIZE='XSMALL' WAREHOUSE_TYPE='STANDARD'
 AUTO_SUSPEND=60 AUTO_RESUME=TRUE INITIALLY_SUSPENDED=TRUE
 STATEMENT_TIMEOUT_IN_SECONDS=60 STATEMENT_QUEUED_TIMEOUT_IN_SECONDS=30;
ALTER WAREHOUSE {{WH}} SET RESOURCE_MONITOR={{MONITOR}};
GRANT USAGE, OPERATE ON WAREHOUSE {{WH}} TO ROLE {{ROLE}};
CREATE DATABASE IF NOT EXISTS {{DB}};
GRANT USAGE, CREATE SCHEMA ON DATABASE {{DB}} TO ROLE {{ROLE}};
GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE {{ROLE}};
USE ROLE {{ROLE}};
USE SECONDARY ROLES NONE;
CREATE SCHEMA IF NOT EXISTS {{DB}}.APP;
CREATE STAGE IF NOT EXISTS {{DB}}.APP.RELEASES;

