CREATE DATABASE IF NOT EXISTS {{DB}};
CREATE SCHEMA IF NOT EXISTS {{DB}}.RAW;
CREATE SCHEMA IF NOT EXISTS {{DB}}.CORE;
CREATE SCHEMA IF NOT EXISTS {{DB}}.AI;
CREATE TABLE IF NOT EXISTS {{DB}}.RAW.CUSTOMERS (
 CUSTOMER_ID VARCHAR NOT NULL, PAYLOAD VARIANT NOT NULL,
 FIXTURE_HASH VARCHAR NOT NULL, LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS {{DB}}.RAW.LOANS (
 LOAN_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, PAYLOAD VARIANT NOT NULL,
 FIXTURE_HASH VARCHAR NOT NULL, LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS {{DB}}.RAW.PAYMENTS (
 PAYMENT_ID VARCHAR NOT NULL, LOAN_ID VARCHAR NOT NULL, PAYLOAD VARIANT NOT NULL,
 FIXTURE_HASH VARCHAR NOT NULL, LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS {{DB}}.RAW.INTERACTIONS (
 INTERACTION_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, CHANNEL VARCHAR NOT NULL,
 TS TIMESTAMP_TZ NOT NULL, TEXT VARCHAR NOT NULL, EVIDENCE_TEXT VARCHAR NOT NULL,
 OFFLINE_SIGNALS VARIANT NOT NULL, SOURCE_HASH VARCHAR NOT NULL,
 FIXTURE_HASH VARCHAR NOT NULL, LOADED_AT TIMESTAMP_TZ NOT NULL
);
CREATE TABLE IF NOT EXISTS {{DB}}.AI.INTERACTION_SIGNALS (
 INTERACTION_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL, SOURCE_HASH VARCHAR NOT NULL,
 PROVIDER VARCHAR NOT NULL, INTENT_RESULT VARIANT, SENTIMENT_RESULT VARIANT,
 ENTITY_RESULT VARIANT, GENERATED_AT TIMESTAMP_TZ NOT NULL
);
