CREATE OR REPLACE VIEW {{DB}}.CORE.CUSTOMER_360 AS
WITH ACTIVE AS (
 SELECT CUSTOMER_ID,
 COUNT(*) AS ACTIVE_LOANS,
 SUM(PAYLOAD:outstanding::NUMBER(18,2)) AS OUTSTANDING,
 SUM(PAYLOAD:emi::NUMBER(18,2)) AS TOTAL_EMI,
 MAX(PAYLOAD:current_dpd::INTEGER) AS CURRENT_DPD
 FROM {{DB}}.RAW.LOANS WHERE PAYLOAD:status::VARCHAR = 'ACTIVE'
 GROUP BY CUSTOMER_ID
), PAYMENT_HISTORY AS (
 SELECT L.CUSTOMER_ID, COUNT(*) AS PAYMENT_COUNT,
 COUNT_IF(P.PAYLOAD:status::VARCHAR = 'PAID') AS PAID_COUNT,
 COUNT_IF(P.PAYLOAD:status::VARCHAR = 'BOUNCED') AS BOUNCE_COUNT
 FROM {{DB}}.RAW.PAYMENTS P JOIN {{DB}}.RAW.LOANS L ON P.LOAN_ID=L.LOAN_ID
 WHERE L.PAYLOAD:status::VARCHAR='ACTIVE' GROUP BY L.CUSTOMER_ID
), INTERACTION_HISTORY AS (
 SELECT CUSTOMER_ID, COUNT(*) AS INTERACTION_COUNT, MAX(TS) AS LAST_INTERACTION
 FROM {{DB}}.RAW.INTERACTIONS GROUP BY CUSTOMER_ID
)
SELECT C.CUSTOMER_ID, C.PAYLOAD:full_name::VARCHAR AS FULL_NAME,
 C.PAYLOAD:city::VARCHAR AS CITY, C.PAYLOAD:segment::VARCHAR AS SEGMENT,
 C.PAYLOAD:monthly_income::NUMBER(18,2) AS MONTHLY_INCOME,
 C.PAYLOAD:consent_calls::BOOLEAN AS CONSENT_CALLS,
 C.PAYLOAD:consent_marketing::BOOLEAN AS CONSENT_MARKETING,
 C.PAYLOAD:dnd::BOOLEAN AS DND,
 COALESCE(A.ACTIVE_LOANS,0) AS ACTIVE_LOANS, COALESCE(A.OUTSTANDING,0) AS OUTSTANDING,
 COALESCE(A.TOTAL_EMI,0) AS TOTAL_EMI, COALESCE(A.CURRENT_DPD,0) AS CURRENT_DPD,
 A.TOTAL_EMI / NULLIF(C.PAYLOAD:monthly_income::NUMBER(18,2),0) AS FOIR,
 COALESCE(P.PAYMENT_COUNT,0) AS PAYMENT_COUNT, COALESCE(P.PAID_COUNT,0) AS PAID_COUNT,
 COALESCE(P.BOUNCE_COUNT,0) AS BOUNCE_COUNT,
 COALESCE(I.INTERACTION_COUNT,0) AS INTERACTION_COUNT, I.LAST_INTERACTION,
 TRUE AS SYNTHETIC
FROM {{DB}}.RAW.CUSTOMERS C LEFT JOIN ACTIVE A USING (CUSTOMER_ID)
LEFT JOIN PAYMENT_HISTORY P USING (CUSTOMER_ID) LEFT JOIN INTERACTION_HISTORY I USING (CUSTOMER_ID);

CREATE OR REPLACE VIEW {{DB}}.CORE.INTERACTION_EVIDENCE AS
SELECT INTERACTION_ID, CUSTOMER_ID, CHANNEL, TS, EVIDENCE_TEXT, SOURCE_HASH,
 OFFLINE_SIGNALS:intent::VARCHAR AS OFFLINE_INTENT,
 OFFLINE_SIGNALS:sentiment::FLOAT AS OFFLINE_SENTIMENT
FROM {{DB}}.RAW.INTERACTIONS;
