CREATE CORTEX SEARCH SERVICE IF NOT EXISTS {{DB}}.AI.INTERACTION_SEARCH
 ON EVIDENCE_TEXT
 ATTRIBUTES CUSTOMER_ID, INTERACTION_ID, CHANNEL
 WAREHOUSE = {{WH}}
 TARGET_LAG = '1 hour'
 INITIALIZE = ON_SCHEDULE
 REQUEST_LOGGING = FALSE
 AUTO_SUSPEND = 1800
AS SELECT EVIDENCE_TEXT, CUSTOMER_ID, INTERACTION_ID, CHANNEL, TS
FROM {{DB}}.RAW.INTERACTIONS;
