-- Synthetic hackathon review ledger. This does not execute financial changes.
CREATE TABLE IF NOT EXISTS {{DB}}.APP.DEMO_REVIEWS (
 REQUEST_ID VARCHAR NOT NULL, CUSTOMER_ID VARCHAR NOT NULL,
 REQUESTED_BY VARCHAR NOT NULL, DECISION_HASH VARCHAR NOT NULL,
 DECISION VARIANT NOT NULL, STATUS VARCHAR NOT NULL,
 CREATED_AT TIMESTAMP_TZ NOT NULL, REVIEWED_AT TIMESTAMP_TZ,
 REVIEWED_BY VARCHAR, REVIEW_NOTE VARCHAR
);

