-- ONE-TIME PRIVATE ANALYTICS SETUP. Review and run as the account/schema owner.
-- This file creates no warehouse/user, schedules no task, and loads no data.
-- Grant the role separately to an approved key-pair service user.
-- Never grant these objects to SAMVAAD_PUBLIC_READER or the public website role.
USE ROLE ACCOUNTADMIN;
CREATE SCHEMA IF NOT EXISTS SAMVAAD_STAGING.RELATIONSHIP;
CREATE ROLE IF NOT EXISTS SAMVAAD_RELATIONSHIP_SYNC;
CREATE TABLE IF NOT EXISTS SAMVAAD_STAGING.RELATIONSHIP.CUSTOMER_PROJECTIONS (
  CUSTOMER_ID VARCHAR NOT NULL,
  VERSION NUMBER(18,0) NOT NULL,
  EVENT_HASH VARCHAR(64) NOT NULL,
  EVENT_ID VARCHAR NOT NULL,
  PAYLOAD VARIANT NOT NULL,
  SYNCED_AT TIMESTAMP_TZ NOT NULL,
  CONSTRAINT RELATIONSHIP_CUSTOMER_ID_PK PRIMARY KEY (CUSTOMER_ID)
);
COMMENT ON TABLE SAMVAAD_STAGING.RELATIONSHIP.CUSTOMER_PROJECTIONS IS
  'Private operational customer projections; contacts may contain PII. SINGLE WRITER required: standard-table PRIMARY KEY is not enforced. No public snapshot promotion.';
GRANT USAGE ON DATABASE SAMVAAD_STAGING TO ROLE SAMVAAD_RELATIONSHIP_SYNC;
GRANT USAGE ON SCHEMA SAMVAAD_STAGING.RELATIONSHIP TO ROLE SAMVAAD_RELATIONSHIP_SYNC;
GRANT SELECT, INSERT, UPDATE ON TABLE SAMVAAD_STAGING.RELATIONSHIP.CUSTOMER_PROJECTIONS TO ROLE SAMVAAD_RELATIONSHIP_SYNC;
GRANT USAGE ON WAREHOUSE SAMVAAD_XS TO ROLE SAMVAAD_RELATIONSHIP_SYNC;
